<?php

use EvolutionCMS\aSocialAuth\Http\Controllers\CredentialsController;
use EvolutionCMS\aSocialAuth\Http\Controllers\SocialCallbackController;
use EvolutionCMS\aSocialAuth\Http\Controllers\SocialLinkController;
use EvolutionCMS\aSocialAuth\Http\Controllers\SocialLoginController;
use EvolutionCMS\aSocialAuth\Http\Middleware\VerifyRequestToken;
use EvolutionCMS\aSocialAuth\Support\Config;
use Illuminate\Support\Facades\Route;

/**
 * Every URL is assembled from config — see the `routes` block in
 * config/aSocialAuth.php. Nothing here hardcodes a path, so a site that wants
 * /auth/ instead of /asocialauth/ changes one value and the callback URLs follow.
 */

if (!Config::routesEnabled()) {
    return;
}

$providerPattern = Config::providerPattern();

Route::prefix(Config::getRoutePrefix())
    ->middleware(Config::routeMiddleware())
    ->group(function () use ($providerPattern) {

        // The e-mail-and-password forms. Registered before {provider} because
        // that route's slug pattern would otherwise match a bare "login".
        //
        // These are POST and CSRF-checked: unlike the provider legs, they are
        // ordinary submissions from a page we rendered.
        //
        // The check is VerifyRequestToken, not the core's `csrf` alias, and the
        // difference matters. The core's middleware skips verification entirely
        // when there is no manager session — reasonable for the core, whose
        // state-changing endpoints all sit behind one, and wrong here, where
        // every one of these routes is aimed at a *front-end* user who has
        // `webValidated` and never `mgrValidated`. Using `csrf` would leave
        // these open to cross-site POSTs while looking protected on the route
        // list. See the middleware for what that would allow.
        Route::post(Config::routePattern('credentials_login'), [CredentialsController::class, 'login'])
            ->middleware(VerifyRequestToken::class)
            ->name(Config::routeName('credentials.login'));

        Route::post(Config::routePattern('credentials_register'), [CredentialsController::class, 'register'])
            ->middleware(VerifyRequestToken::class)
            ->name(Config::routeName('credentials.register'));

        Route::post(Config::routePattern('credentials_recover'), [CredentialsController::class, 'recover'])
            ->middleware(VerifyRequestToken::class)
            ->name(Config::routeName('credentials.recover'));

        Route::post(Config::routePattern('credentials_reset'), [CredentialsController::class, 'reset'])
            ->middleware(VerifyRequestToken::class)
            ->name(Config::routeName('credentials.reset'));

        // Claim an e-mail address for the signed-in account — the Telegram
        // sign-up filling in what the provider never supplied.
        Route::post(Config::routePattern('credentials_email'), [CredentialsController::class, 'email'])
            ->middleware(VerifyRequestToken::class)
            ->name(Config::routeName('credentials.email'));

        // Prove it. A GET from a mail client, so no CSRF token can accompany it;
        // the unguessable token in the link is the credential, and following it
        // only ever confirms an address the account itself asked for.
        Route::get(Config::routePattern('credentials_verify'), [CredentialsController::class, 'verify'])
            ->name(Config::routeName('credentials.verify'));

        // The provider callback. Registered first among the provider routes so
        // that a `patterns` override making the login route greedy cannot
        // swallow it.
        //
        // GET *and* POST, because the two families of provider answer
        // differently and both have to land here:
        //
        //   OAuth 2 (Google, Facebook, Discord, …) and OpenID with an indirect
        //   GET response (Steam) redirect the browser back with the result in
        //   the query string.
        //
        //   Apple sets response_mode=form_post, and OpenID 2.0 permits a POST
        //   indirect response for payloads too large for a URL. Those arrive as
        //   a cross-site form submission. A GET-only route would 404 them, which
        //   is exactly the kind of failure that only shows up once a site
        //   enables Apple.
        //
        // No CSRF either way, and that is not an oversight: the request is made
        // by a third party and cannot carry our token. HybridAuth's `state`
        // parameter — generated by us, parked in the session, checked on return —
        // is the protection for this leg. Note that a cross-site POST needs the
        // session cookie to be SameSite=None; Secure, or the session it must be
        // checked against will not be sent. See the README.
        Route::match(['get', 'post'], Config::routePattern('callback'), SocialCallbackController::class)
            ->where('provider', $providerPattern)
            ->name(Config::routeName('callback'));

        // Start adding a second identity to the account already signed in.
        Route::get(Config::routePattern('link'), [SocialLinkController::class, 'start'])
            ->where('provider', $providerPattern)
            ->name(Config::routeName('link'));

        // Detach an identity. POST and CSRF-protected: this one is an ordinary
        // form submission from a page we rendered, so there is no reason to
        // exempt it, and unlinking on a GET would be triggerable from an <img>.
        Route::post(Config::routePattern('unlink'), [SocialLinkController::class, 'unlink'])
            ->where('provider', $providerPattern)
            ->middleware(VerifyRequestToken::class)
            ->name(Config::routeName('unlink'));

        // Start a sign-in. Least specific, so it goes last.
        Route::get(Config::routePattern('login'), SocialLoginController::class)
            ->where('provider', $providerPattern)
            ->name(Config::routeName('login'));
    });
